name: yanmar_app
description: A new Flutter project.
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.6.7
  go_router: ^13.2.0
  supabase_flutter: ^2.5.11
  intl: ^0.19.0
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham/GothamBlack.ttf
        - asset: assets/fonts/Gotham/GothamBold.ttf
          weight: 700
        - asset: assets/fonts/Gotham/GothamLight.ttf
          weight: 400
        - asset: assets/fonts/Gotham/GothamMedium.ttf
          weight: 500
