name: yanmar_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.6.7
  go_router: ^13.2.0
  supabase_flutter: ^2.5.11
  intl: ^0.19.0
  equatable: ^2.0.5
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
